# Generated by Django 5.2.15 on 2026-06-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_provider_add_social_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='팔로우 일시')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='팔로워')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉')),
            ],
            options={
                'db_table': 'follow',
                'indexes': [models.Index(fields=['follower', '-created_at'], name='follow_follower_idx'), models.Index(fields=['following', '-created_at'], name='follow_following_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='follow_no_self_follow')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
