# Generated by Django 5.2.14 on 2026-06-22 05:42

import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_add_like_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='스티커명')),
                ('category', models.CharField(choices=[('sticker', '스티커'), ('frame', '프레임'), ('bubble', '말풍선'), ('icon', '아이콘'), ('background', '배경'), ('tape', '테이프')], default='sticker', max_length=20, verbose_name='카테고리')),
                ('image', models.ImageField(upload_to=records.models.sticker_upload_to, verbose_name='이미지')),
                ('emoji_fallback', models.CharField(blank=True, help_text='이미지 없이 이모지로 표시할 경우', max_length=10, verbose_name='이모지 대체')),
                ('tone', models.CharField(blank=True, max_length=50, verbose_name='CSS 톤 클래스')),
                ('is_default', models.BooleanField(default=False, help_text='True면 신규 가입 유저에게 자동 부여', verbose_name='기본 제공')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sticker_asset',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_type', models.CharField(choices=[('default', '기본 제공'), ('reward', '보상'), ('purchase', '구매'), ('event', '이벤트')], default='default', max_length=20, verbose_name='획득 방법')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='획득일')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='records.stickerasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sticker',
                'ordering': ['sticker__order', 'sticker__id'],
                'unique_together': {('user', 'sticker')},
            },
        ),
    ]
