# Generated by Django 5.2.14 on 2026-06-23 08:49
from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_allow_null_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerasset',
            name='category',
            field=models.CharField(choices=[('sticker', '스티커'), ('frame', '프레임'), ('bubble', '말풍선')], default='sticker', max_length=20, verbose_name='카테고리'),
        ),
    ]

