# Generated by Django 5.2.14 on 2026-05-29 06:44

import works.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='poster_image',
            field=models.URLField(blank=True, max_length=500, validators=[works.validators.validate_poster_url], verbose_name='포스터 URL'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['-release_date', 'title'], name='work_release_title_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['work_type'], name='work_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('source', 'external_id'), name='work_source_external_id_uniq'),
        ),
    ]
