# Generated by Django 5.2.14 on 2026-06-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': [models.OrderBy(models.F('release_date'), descending=True, nulls_last=True), 'title']},
        ),
    ]
