# Generated by Django 5.0.6 on 2026-05-16 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='앨범명')),
                ('description', models.TextField(blank=True, verbose_name='앨범 설명')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='커버 이미지 URL')),
                ('visibility', models.CharField(choices=[('public', '전체 공개'), ('friends', '친구 공개'), ('private', '비공개')], default='private', max_length=20, verbose_name='공개 범위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'db_table': 'album',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 시각')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
            ],
            options={
                'db_table': 'album_record',
                'ordering': ['-added_at'],
                'unique_together': {('album', 'record')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='records',
            field=models.ManyToManyField(related_name='albums', through='albums.AlbumRecord', to='records.record'),
        ),
    ]
