# Generated by Django 5.2.14 on 2026-06-22 00:47

import works.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, validators=[works.validators.validate_poster_url], verbose_name='커버 이미지 URL'),
        ),
    ]
