# Generated by Django 5.2.15 on 2026-06-22 02:00

import django.db.models.deletion
import shares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0003_add_like_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('category', models.CharField(choices=[('minimal', '미니멀'), ('emotional', '감성'), ('retro', '레트로'), ('cute', '큐트'), ('dark', '다크')], max_length=20, verbose_name='카테고리')),
                ('thumbnail', models.URLField(blank=True, max_length=500, verbose_name='썸네일 URL')),
                ('background_image', models.URLField(blank=True, max_length=500, verbose_name='배경 이미지 URL')),
                ('layout_schema', models.JSONField(default=dict, help_text='텍스트/이미지 슬롯의 위치·크기 정의 JSON', verbose_name='레이아웃 스키마')),
                ('description_for_ai', models.TextField(blank=True, help_text='AI가 템플릿 선택 시 참고할 설명', verbose_name='AI 설명문')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'db_table': 'card_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShareCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(default=dict, help_text='AI가 반환한 레이아웃 JSON', verbose_name='AI 배치 데이터')),
                ('image', models.ImageField(blank=True, upload_to=shares.models.share_card_upload_to, verbose_name='공유 카드 이미지')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='사용된 AI 모델')),
                ('ai_prompt_tokens', models.IntegerField(default=0, verbose_name='프롬프트 토큰 수')),
                ('ai_response_tokens', models.IntegerField(default=0, verbose_name='응답 토큰 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_cards', to='records.record', verbose_name='원본 기록')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_cards', to='shares.cardtemplate', verbose_name='사용된 템플릿')),
            ],
            options={
                'db_table': 'share_card',
                'ordering': ['-created_at'],
            },
        ),
    ]
